package com.naeemdev.githubuser.domain.model


data class UserDetailModelD(
    var login: String = "",
    var avatarUrl: String = "",
    var gravatarId: String = "",
    var url: String = "",
    var htmlUrl: String = "",
    var followersUrl: String = "",
    var followingUrl: String = "",
    var gistsUrl: String = "",
    var starredUrl: String = "",
    var subscriptionsUrl: String = "",
    var organizationsUrl: String = "",
    var reposUrl: String = "",
    var eventsUrl: String = "",
    var receivedEventsUrl: String = "",
    var type: String = "",
    var siteAdmin: Boolean = false,
    var fullName: String = "",
    var company: String = "",
    var blog: String = "",
    var location: String = "",
    var email: String = "",
    var isHireAble: Boolean = false,
    var bio: String = "",
    var twitterUsername: String = "",
    var publicRepos: Int? = null,
    var publicGists: Int? = null,
    var followers: Int?= null,
    var following: Int? = null,
    var createdAt: String = "",
    var updatedAt: String = "",
)